### PR TITLE
Update/2.4.6

### PR DESCRIPTION
**Pull request by cbouss**
Changes:
- Update to 2.4.6

https://anaconda.atlassian.net/browse/PKG-1263
https://github.com/explosion/srsly/tree/v2.4.6

### CODE REVIEW

**Comment by M-Waszkiewicz-Anaconda** [comment]
looks good to me

**Review by M-Waszkiewicz-Anaconda — APPROVED** [review]
looks good to me, good job!

**Review by danpetry — APPROVED** [review]
Could we pin to cython ==0.25? Otherwise, looks good

**Comment by cbouss** [comment]
> Could we pin to cython ==0.25? Otherwise, looks good

We shouldn't otherwise we'll have trouble on combinations where 0.25 is not available.
It is actually fine to use the latest version of cython available.

**Pull request merged**
